### ISSUE TITLE
Install errors at Ubuntu (Xubuntu)

### ISSUE THREAD

**Issue by andreas-roehler** [aprolog-lang/aprolog#4]
The OCaml toplevel, version 4.08.1
Linux XYZ 5.4.0-42-generic #46-Ubuntu SMP Fri Jul 10 00:24:02 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
Make install signals error as root and respective as user. Executable as bin is built and opens an interactive shell with a-prolog prompt.

Below the result from root is given:

./configure.sh /root/local/aprolog
Configuring for install directory "/root/local/aprolog"...
make -C src aprolog
make[1]: Verzeichnis „/home/my-name/arbeit/aprolog-master/src“ wird betreten
ocamlopt.opt -c config.ml -o config.cmx
ocamlopt.opt -c main.ml -o main.cmx
File "main.ml", line 406, characters 2-11507:
406 | ..match decl with
407 |     Query (t) -> handle_query t sg idx
408 |   | SaveDirective(filename,"no_backtrack",decl) ->
409 |       start_save_to_file (false);
410 |       let sg,idx = run1 pos decl sg idx in
...
690 |   | GenerateDirective("forallstar") ->
691 |      let decls = Negelim.generate_forallstars sg in
692 |      if !debug then print_generated decls;
693 |      run sg idx decls, idx
Warning 8: this pattern-matching is not exhaustive.
Here is an example of a case that is not matched:
GenerateDirective ""
ocamlopt.opt str.cmxa flags.cmx config.cmx util.cmx monad.cmx printer.cmx pos.cmx var.cmx unique.cmx trie.cmx varmap.cmx varset.cmx types.cmx fixity.cmx nstbl.cmx absyn.cmx lineno.cmx lexer.cmx parser.cmx perm.cmx internal.cmx isym.cmx termgraph.cmx tcenv.cmx translate.cmx index.cmx subst.cmx eval.cmx explain.cmx unify.cmx tc.cmx runtime.cmx solve.cmx boundsolve.cmx string_set.cmx string_map.cmx dependency_graph.cmx negelim.cmx check.cmx main.cmx -o aprolog
make[1]: Verzeichnis „/home/my-name/arbeit/aprolog-master/src“ wird verlassen
cp src/aprolog bin
./install.sh . /root/local/aprolog
mkdir: das Verzeichnis »/root/local/aprolog“ kann nicht angelegt werden: Datei oder Verzeichnis nicht gefunden
mkdir: das Verzeichnis »/root/local/aprolog/bin“ kann nicht angelegt werden: Datei oder Verzeichnis nicht gefunden
mkdir: das Verzeichnis »/root/local/aprolog/lib“ kann nicht angelegt werden: Datei oder Verzeichnis nicht gefunden
mkdir: das Verzeichnis »/root/local/aprolog/examples“ kann nicht angelegt werden: Datei oder Verzeichnis nicht gefunden
mkdir: das Verzeichnis »/root/local/aprolog/examples/simple“ kann nicht angelegt werden: Datei oder Verzeichnis nicht gefunden
mkdir: das Verzeichnis »/root/local/aprolog/doc“ kann nicht angelegt werden: Datei oder Verzeichnis nicht gefunden
Could not create install directory /root/local/aprolog
make: *** [Makefile:37: install] Fehler 1
---
Thanks working at that,
Andreas

**Comment by jamescheney** [comment]
The install script is really primitive, and assumes that the parent of the target directory `$HOME/local/aprolog` already exists, so the errors appear to be because `$HOME/local` doesn't already exist.  It doesn't create this directory if it is missing.  You can work around this either by creating this directory yourself, or by modifying the INSTALL variable in the Makefile to point somewhere else such that the parent directory of the intended `aprolog` install directory does exist already.

**Comment by jamescheney** [comment]
Closed by 46fceba which gives a more informative warning if the parent of the intended install dir doesn't exist.
