### ISSUE TITLE
Is Transpose correctly handled here?

### ISSUE THREAD

**Issue by np** [aprolog-lang/aprolog#5]
As I read it the support of `(a ~ b) t` is defined as `{a,b}` and seems to ignore `t`.

This is here:
  https://github.com/aprolog-lang/aprolog/blob/14b73cda4761f4b6dcd84cd3b732609885b4a4d2/src/absyn.ml#L523C2-L523C2

Same remark for `fvs` and `fas`.

Am I reading this correctly?

**Comment by jamescheney** [comment]
Huh.  That is indeed strange and probably wrong.  However, I'm not sure `Absyn.supp` is ever used anymore - I can find only a few calls to the other two, mostly in negation elimination which is not enabled by default.

The equivalent functions for `Internal.term` (which are widely/frequently used) do not have this problem.

**Comment by np** [comment]
Thanks!

While I noticed that `Absyn.supp` was not used anymore `Absyn.fvs` is used in translate.
